from api import Exercise

x = Exercise("ten_minutes_abs/")
x.add_exercise("Side Hop", 30, 10)
x.add_exercise("Inchworms", 30, 10)
x.add_exercise("Trunk Rotation", 30, 10)
x.add_exercise("Butt Kicks", 30, 10)
x.add_exercise("Lunges", 30, 10)
x.add_exercise("Jumping Jacks", 30, 10)
x.add_exercise("Squats", 30, 10)
x.add_exercise("Squat Kicks", 30, 10)
x.add_exercise("Modified Burpees", 30, 20)
x.add_exercise("Crunches with Legs Raised", 50, 10)
x.add_exercise("Reclined Oblique Twist", 50, 10)
x.add_exercise("Scissors", 50, 10)
x.add_exercise("X-Man Crunch", 50, 10)
x.add_exercise("Leg Raises", 50, 10)
x.add_exercise("Bicycle Crunches", 50, 10)
x.add_exercise("Swimmer and Superman", 50, 10)
x.add_exercise("Side Plank Front Kick Right", 50, 10)
x.add_exercise("Side Plank Front Kick Left", 50, 10)
x.add_exercise("Russian Twist", 50, 10)
x.add_exercise("Flutter Kicks", 50, 10)
x.add_exercise("Reclined Oblique Twist", 50, 10)
x.add_exercise("Crunch with Legs Raised", 50, 20)
x.add_exercise("Jumping Jacks", 20, 10)
x.add_exercise("Jumping Jacks", 20, 10)
x.add_exercise("Jumping Jacks", 20, 10)
x.add_exercise("Jumping Jacks", 20, 10)
x.add_exercise("Modified Burpees", 20, 10)
x.add_exercise("Modified Burpees", 20, 10)
x.add_exercise("Modified Burpees", 20, 10)
x.add_exercise("Modified Burpees", 20, 10)
x.add_exercise("Straight Leg Bounds", 20, 10)
x.add_exercise("Straight Leg Bounds", 20, 10)
x.add_exercise("Straight Leg Bounds", 20, 10)
x.add_exercise("Straight Leg Bounds", 20, 10)
x.add_exercise("Skater Jump", 20, 10)
x.add_exercise("Skater Jump", 20, 10)
x.add_exercise("Skater Jump", 20, 10)
x.add_exercise("Skater Jump", 20, 10)
x.add_exercise("Knee Push-Ups", 20, 10)
x.add_exercise("Knee Push-Ups", 20, 10)
x.add_exercise("Knee Push-Ups", 20, 10)
x.add_exercise("Knee Push-Ups", 20, 10)
x.add_exercise("Plank Jacks", 20, 10)
x.add_exercise("Plank Jacks", 20, 10)
x.add_exercise("Plank Jacks", 20, 10)
x.add_exercise("Plank Jacks", 20, 10)
x.add_exercise("Triceps Stretch Right", 30, 0)
x.add_exercise("Triceps Stretch Left", 30, 0)
x.add_exercise("Right Quad Stretch with Wall", 30, 0)
x.add_exercise("Left Quad Stretch with Wall", 30, 0)
x.add_exercise("Calf Stretch Left", 30, 0)
x.add_exercise("Calf Stretch Right", 30, 0)
x.add_exercise("Cobra Stretched", 30, 0)
x.play_exercise()